# Generated by Django 5.0.6 on 2024-05-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('topic', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_positions', to='geo_view.article')),
            ],
        ),
    ]
