name: geo_view


services:
  app.base:
    image: geo_view
    build:
      dockerfile: docker/Dockerfile
      context: ..
    depends_on:
      postgres:
        condition: service_healthy
    command: django-admin migrate

  app.web:
    extends:
      service: app.base
    command: django-admin runserver 0.0.0.0:8000
    volumes:
      - ../geo_view:/usr/local/lib/python3.12/site-packages/geo_view
    ports:
      - 8000:8000
    expose:
      - 5432
    healthcheck:
      test: curl localhost:8000/search || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

  app.import:
    extends:
      service: app.base
    volumes:
      - ./scripts:/scripts
      - ./volumes/news:/news
    command: bash -c "bash /scripts/import.sh && bash /scripts/process-locations.sh"
    depends_on:
      app.base:
        condition: service_completed_successfully
    profiles:
      - import

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_view
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d geo_view" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - "./volumes/redis-data:/data"

  nominatim:
    image: mediagis/nominatim:4.4
    environment:
      IMPORT_STYLE: street
      PBF_PATH: /nominatim/data/russia-latest.osm.pbf
    ports:
      - 8080:8080
    volumes:
      - "./volumes/nominatim-data:/nominatim/data/"
      - "./volumes/nominatim-flatnode:/nominatim/flatnode"
      - "./volumes/nominatim-postgres-data:/var/lib/postgresql/14/main"
