name: geo_view


services:
  base-app:
    image: geo_view
    build:
      dockerfile: docker/Dockerfile
      context: ..
    depends_on:
      postgres:
        condition: service_healthy
    command: django-admin migrate

  web-app:
    extends:
      service: base-app
    command: django-admin runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - 5432
    healthcheck:
      test: curl localhost:8000 || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:latest
    container_name: django_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_view
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d geo_view" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  import:
    extends:
      service: base-app
    volumes:
      - ./scripts:/scripts
      - ./volumes/news:/news
    command: bash /scripts/import.sh
    depends_on:
      web-app:
        condition: service_healthy
    profiles:
      - import

#  nominatim:
#    image: mediagis/nominatim:4.4
#    environment:
#      PBF_PATH: /nominatim/data/russia-latest.osm.pbf
#    ports:
#      - "8080:8080"
#    volumes:
#      - "./volumes/nominatim-data:/nominatim/data/"
#      - "./volumes/nominatim-flatnode:/nominatim/flatnode"
#      - "./volumes/nominatim-postgres-data:/var/lib/postgresql/14/main"
#
#  my-nominatim:
#    image: my-nominatim:test
#    build: nominatim
#    environment:
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: postgres
#      POSTGRES_PASS: postgres
